main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Examples
    url: /example/
    weight: 4
  - name: Assignments
    url: /assignment/
    weight: 5
  - name: '<i class="fab fa-slack"></i>'
    url: "https://join.slack.com/t/msu-qs62738/shared_invite/zt-10u63bf0n-b0cePmz9NDhhw3MSUPBP5A"
    weight: 6

content: 
  - name: Course content
    weight: 2
examples:
  - name: Examples
    weight: 2
assignments:
  - name: Labs
    weight: 2
  - name: Projects
    weight: 3
resource:
  - name: Resources
    weight: 1
  - name: Guides
    weight: 2
