---
title: "Schedule"
slug: schedule
---

Below is a roadmap for the semester. Note that this will inevitably change from the first day you access this course. However, whatever is listed below should be considered canon. Accordingly, you should visit this page frequently throughout the term.

As mentioned in the syllabus, the course is structured by topics; each week introduces a new topic. Moreover, every week is divided into three important sections that you should engage with. 

### Overview

The class is structured with three distinct bits. First, the Tuesday lecture will give an overview of the topic for the week. Next, the Thursday lecture will have a short, practical lecture and an activity which is designed to give you hands-on experience and a greater understanding of the broader material. Finally, you will complete weekly writings (short) and labs (also short; requiring coding in `R`). Out of class, you will complete readings and complete assignments.

- [**Content**](/content/) (<i class="fas fa-book-reader"></i>): This page contains the readings for the topic. These pages should be read completely. Lectures are *not* an exact replication of the written content; on the contrary, the lectures are intended to keep you focused on the high-level ideas, while the readings are broader and more comprehensive. Accordingly, lectures are shorter than the (often quite lengthy) written content.

- [**Examples**](/example/) (<i class="fas fa-laptop-code"></i>): This page the material that we will discuss in Thursday classes. In addition to teaching specific content, there are many more `R` code examples. These are intended as a useful reference to various functions that you will need when working on (nearly) weekly labs and your group project.

- [**Assignments**](/assignment/) (<i class="fas fa-pencil-ruler"></i>): This page contains the instructions for the weekly lab (1–3 brief tasks) and for the two mini projects + final project. **Labs are due by 11:59 PM (Eastern) on the Monday after they're posted.**

### Office Hours (TA) Monday (time TBA, 1.5 hours in morning) via Zoom

The teaching assistant for this course (Sam Tucker; tucke130@msu.edu) will host office each week to help promote additional understanding. I highly encourage you to utilize this resource, especially if you struggle with basic `R` programming.

### Prof. K's Office Hours Wednesdays 2:00 pm to 3:00 pm [via Zoom](https://msu.zoom.us/j/91759862734?pwd=VDliRHdoQ3N4L3V4LzNFd3IzcGw2dz09) passcode: DATA

I will hold weekly drop-in office hours on Wednesdays from 2-3pm and via appointment (just ask!). I will be in the Zoom Room from 2-3 pm, but will stay later if and only if someone is there or you have emailed me beforehand to let me know you're planning on coming later. Drop-in office hours are time set aside for **you** to ask questions about the material, the course, the topic, or about life in general. They are a great resource and most faculty are bewildered when students don't use them. 

All office hours are via Zoom as questions will often (but don't always) center around coding and sharing a screen in Zoom is pretty easy. Both the TA and Prof. K will monitor the course slack for questions as well.





:::note
**tl;dr**: You should follow this general process (in order) each week:

- Do everything on the content (<i class="fas fa-book-reader"></i>) page before Tuesday
- Come to the lecture on Tuesday.
- While "in class" on Thursday, work through the example (<i class="fas fa-laptop-code"></i>) page
- Complete the lab (<i class="fas fa-pencil-ruler"></i>) and the weekly writing (assigned in class) before the next Tuesday.
- As needed, attend the lab hours hosted by the TA.
:::

---

`r blogdown::shortcode("schedule")`
