<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Ben Bushong">

  
  
  
    
  
  <meta name="description" content="Preliminaries Code  Load the data Scatterplot matrices Correlograms  Simple regression   Preliminaries For this example, we’re going to use historical weather data from Dark Sky about wind speed and temperature trends for downtown Atlanta (specifically 33.754557, -84.390009) in 2019. We downloaded this data using Dark Sky’s (about-to-be-retired-because-they-were-bought-by-Apple) API using the darksky package.
If you want to follow along with this example, you can download the data below (you’ll likely need to right click and choose “Save Link As…” and place it in a data folder next to your working R script):">

  
  <link rel="alternate" hreflang="en-us" href="https://ssc442.netlify.app/example/05-example/">

  


  
  
  
  <meta name="theme-color" content="#18453B">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7COverpass:400,400i,700,700i&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu5cb5fae69b6b75ece00896ca20e5499a_29457_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu5cb5fae69b6b75ece00896ca20e5499a_29457_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://ssc442.netlify.app/example/05-example/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="Data Analytics">
  <meta property="og:url" content="https://ssc442.netlify.app/example/05-example/">
  <meta property="og:title" content="Introduction to Regression | Data Analytics">
  <meta property="og:description" content="Preliminaries Code  Load the data Scatterplot matrices Correlograms  Simple regression   Preliminaries For this example, we’re going to use historical weather data from Dark Sky about wind speed and temperature trends for downtown Atlanta (specifically 33.754557, -84.390009) in 2019. We downloaded this data using Dark Sky’s (about-to-be-retired-because-they-were-bought-by-Apple) API using the darksky package.
If you want to follow along with this example, you can download the data below (you’ll likely need to right click and choose “Save Link As…” and place it in a data folder next to your working R script):"><meta property="og:image" content="https://ssc442.netlify.app/img/social-image.png">
  <meta property="twitter:image" content="https://ssc442.netlify.app/img/social-image.png"><meta property="og:locale" content="en-us">
  
    
    <meta property="article:modified_time" content="2024-02-08T11:58:37-05:00">
  

  



  


  


  <link rel="shortcut icon" href="https://ssc442.netlify.app/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="https://ssc442.netlify.app/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://ssc442.netlify.app/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://ssc442.netlify.app/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://ssc442.netlify.app/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="https://ssc442.netlify.app/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://ssc442.netlify.app/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="https://ssc442.netlify.app/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="https://ssc442.netlify.app/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content="SSC 442: Data Analytics" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="https://ssc442.netlify.app/img/mstile-144x144.png" />


  <title>Introduction to Regression | Data Analytics</title>

</head>


<body id="top" data-spy="scroll" data-offset="70"
    data-target="#TableOfContents"
    >

    <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


    







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Data Analytics</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Data Analytics</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/syllabus/"><span>Syllabus</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Schedule</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Content</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Examples</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/assignment/"><span>Assignments</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Resources</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://join.slack.com/t/ssc442fall23/shared_invite/zt-21po16rx0-eSBByPJt~4ahKVWqqQaalQ" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Examples</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/00-example/">1: Introduction to R</a>
      </li>
      
      <li >
        <a href="/example/01-example/">2: Visualization I</a>
      </li>
      
      <li >
        <a href="/example/02-example/">3: Visualization II</a>
      </li>
      
      <li >
        <a href="/example/03-example/">4: Visualization III</a>
      </li>
      
      <li >
        <a href="/example/04-example/">5: Uncertainty</a>
      </li>
      
      <li class="active">
        <a href="/example/05-example/">6: Linear Regression I</a>
      </li>
      
      <li >
        <a href="/example/06-example/">7: Linear Regression II</a>
      </li>
      
      <li >
        <a href="/example/07-example/">8: Linear Regression III</a>
      </li>
      
      <li >
        <a href="/example/08-example-notusedfallbreak-2/">8: Shrinkage with LASSO and Ridge</a>
      </li>
      
      <li >
        <a href="/example/09-example/">9: Nonparametric Regression</a>
      </li>
      
      <li >
        <a href="/example/10-example/">10: Bias vs. Variance</a>
      </li>
      
      <li >
        <a href="/example/11-example/">11: Classification</a>
      </li>
      
      <li >
        <a href="/example/12-example/">12: Text As Data</a>
      </li>
      
      <li >
        <a href="/example/13-example/">13: Data Wrangling</a>
      </li>
      
      <li >
        <a href="/example/14-example/">14: Geospatial with R</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Introduction to Regression</h1>

                    

                    
                    <div class="due-date p-2 mb-3 bg-content text-white">
                        Content for Thursday, February 15, 2024
                    </div>
                    

                    

                    <div class="article-style">
                        

<div id="TOC">
<ul>
<li><a href="#preliminaries" id="toc-preliminaries">Preliminaries</a></li>
<li><a href="#code" id="toc-code">Code</a>
<ul>
<li><a href="#load-the-data" id="toc-load-the-data">Load the data</a></li>
<li><a href="#scatterplot-matrices" id="toc-scatterplot-matrices">Scatterplot matrices</a></li>
<li><a href="#correlograms" id="toc-correlograms">Correlograms</a></li>
</ul></li>
<li><a href="#simple-regression" id="toc-simple-regression">Simple regression</a></li>
</ul>
</div>

<div id="preliminaries" class="section level2">
<h2>Preliminaries</h2>
<p>For this example, we’re going to use historical weather data from <a href="https://darksky.net/forecast/33.7546,-84.39/us12/en">Dark Sky</a> about wind speed and temperature trends for downtown Atlanta (<a href="https://www.google.com/maps/place/33°45&#39;16.4%22N+84°23&#39;24.0%22W/@33.754557,-84.3921977,17z/">specifically <code>33.754557, -84.390009</code></a>) in 2019. We downloaded this data using Dark Sky’s (about-to-be-retired-because-they-were-bought-by-Apple) API using the <a href="https://github.com/hrbrmstr/darksky"><strong>darksky</strong> package</a>.</p>
<p>If you want to follow along with this example, you can download the data below (you’ll likely need to right click and choose “Save Link As…” and place it in a <code>data</code> folder next to your working R script):</p>
<ul>
<li><a href="/data/atl-weather-2019.csv"><i class="fas fa-file-csv"></i> <code>atl-weather-2019.csv</code></a></li>
</ul>
</div>
<div id="code" class="section level2">
<h2>Code</h2>
<div id="load-the-data" class="section level3">
<h3>Load the data</h3>
<p>First, we load the libraries we’ll be using:</p>
<pre class="r"><code>library(tidyverse)  # For ggplot, dplyr, and friends
library(patchwork)  # For combining ggplot plots
library(GGally)     # New one, for scatterplot matrices
library(broom)      # For converting model objects to data frames</code></pre>
<p>Then we load the data with <code>read_csv()</code>. This is <code>tidyverse</code>’s CSV reader (base <code>R</code> is <code>read.csv</code>). Here we assume that the CSV file was downloaded and lives in a subfolder named <code>data</code>:</p>
<pre class="r"><code>weather_atl &lt;- read_csv(&quot;data/atl-weather-2019.csv&quot;)</code></pre>
</div>
<div id="scatterplot-matrices" class="section level3">
<h3>Scatterplot matrices</h3>
<p>The foundation of linear regression is corrleation. We can visualize the correlations between pairs of variables with the <code>ggpairs()</code> function in the <strong>GGally</strong> package. For instance, how correlated are high and low temperatures, humidity, wind speed, and the chance of precipitation? We first make a smaller dataset with just those columns, and then we feed that dataset into <code>ggpairs()</code> to see all the correlation information:</p>
<pre class="r"><code>library(GGally)

weather_correlations &lt;- weather_atl %&gt;%
  select(temperatureHigh, temperatureLow, humidity, windSpeed, precipProbability)

ggpairs(weather_correlations)</code></pre>
<p><img src="/example/05-example_files/figure-html/ggpairs-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>It looks like high and low temperatures are extremely highly positively correlated (r = 0.92). Wind speed and temperature are moderately negatively correlated, with low temperatures having a stronger negative correlation (r = -0.45). There’s no correlation whatsoever between low temperatures and the precipitation probability (r = -0.03) or humidity and high temperatures (r = -0.03).</p>
<p>Even though <code>ggpairs()</code> doesn’t use the standard <code>ggplot(...) + geom_whatever()</code> syntax we’re familiar with, it does behind the scenes, so you can add regular ggplot layers to it:</p>
<pre class="r"><code>ggpairs(weather_correlations) + 
  labs(title = &quot;Correlations!&quot;) +
  theme_dark()</code></pre>
<p><img src="/example/05-example_files/figure-html/ggpairs-layers-1.png" width="576" style="display: block; margin: auto;" /></p>
<div class="fyi">
<p><strong>TRY IT</strong></p>
<p>Here’s some code to load data from the Residential Energy Consumption Survey (RECS), a <a href="https://www.eia.gov/consumption/residential/data/2020/">once-a-decade survey of household energy consumption done by the Energy Information Administration.</a>. Use the code here to load the data. I’ve selected a few variables and renamed them to something intuitive. Each observation is a household surveyed by the EIA. The variable named <code>EnergyUsed</code> is the total BTU’s of energy consumed by that household.</p>
<p>Most of the variables are self-explanatory except the following:</p>
<ul>
<li><p><code>AgeOfHome</code> is on a 1-9 scale where 1 is the oldest and 9 is the newest.</p></li>
<li><p><code>HeaterAge</code> is the age of the home’s heater from 1 to 6 where 6 is the oldest and 1 is the newest.</p></li>
<li><p><code>TVSize</code> is on a scale of 1 (smallest) to 4 (largest)</p></li>
<li><p><code>TempHome</code> tells us the home’s thermostat setting when home (in degrees farenheit)</p></li>
</ul>
<p>Your task is to make a ggpairs plot for <code>EnergyUsed</code> and five of the variables in the RECS data. What variables do you think are correlated with total energy use <code>EnergyUsed</code>? And <strong>what can we learn about energy consumption from these correlations?</strong></p>
<pre class="r"><code>RECS = read.csv(&#39;https://www.eia.gov/consumption/residential/data/2009/csv/recs2009_public.csv&#39;, stringsAsFactors = F) %&gt;%
  as_tibble() %&gt;%  
  dplyr::select(EnergyUsed = TOTALBTU,
                ColdDays = HDD65, HotDays = CDD65, SquareFeet = TOTHSQFT, CarsGarage = SIZEOFGARAGE, 
                AgeOfHome = YEARMADERANGE, TreeShade = TREESHAD, TVSize = TVSIZE1, HeaterAge = EQUIPAGE, HasAC = AIRCOND,
                TempHome = TEMPHOME) %&gt;%
  dplyr::filter(HeaterAge != -2 &amp; TempHome !=-2)  # these are NAs</code></pre>
</div>
</div>
<div id="correlograms" class="section level3">
<h3>Correlograms</h3>
<p>Scatterplot matrices typically include way too much information to be used in actual publications. I use them when doing my own analysis just to see how different variables are related, but I rarely polish them up for public consumption. In the readings for today, Claus Wilke showed a type of plot called a <a href="https://serialmentor.com/dataviz/visualizing-associations.html#associations-correlograms"><em>correlogram</em></a> which <em>is</em> more appropriate for publication.</p>
<p>These are essentially heatmaps of the different correlation coefficients. To make these with ggplot, we need to do a little bit of extra data processing, mostly to reshape data into a long, tidy format that we can plot. Here’s how.</p>
<p>First we need to build a correlation matrix of the main variables we care about. Ordinarily the <code>cor()</code> function in R takes two arguments—x and y—and it will return a single correlation value. If you feed a data frame into <code>cor()</code> though, it’ll calculate the correlation between each pair of columns. <span style="     color: red !important;">But be careful - don’t feed in hundreds of variables by accident!</span></p>
<pre class="r"><code># Create a correlation matrix
things_to_correlate &lt;- weather_atl %&gt;%
  select(temperatureHigh, temperatureLow, humidity, windSpeed, precipProbability) %&gt;%
  cor()

things_to_correlate</code></pre>
<pre><code>##                   temperatureHigh temperatureLow humidity windSpeed precipProbability
## temperatureHigh              1.00          0.920   -0.030    -0.377            -0.124
## temperatureLow               0.92          1.000    0.112    -0.450            -0.026
## humidity                    -0.03          0.112    1.000     0.011             0.722
## windSpeed                   -0.38         -0.450    0.011     1.000             0.196
## precipProbability           -0.12         -0.026    0.722     0.196             1.000</code></pre>
<p>The two halves of this matrix (split along the diagonal line) are identical, so we can remove the lower triangle with this code (which will set all the cells in the lower triangle to <code>NA</code>):</p>
<pre class="r"><code># Get rid of the lower triangle
things_to_correlate[lower.tri(things_to_correlate)] &lt;- NA
things_to_correlate</code></pre>
<pre><code>##                   temperatureHigh temperatureLow humidity windSpeed precipProbability
## temperatureHigh                 1           0.92    -0.03    -0.377            -0.124
## temperatureLow                 NA           1.00     0.11    -0.450            -0.026
## humidity                       NA             NA     1.00     0.011             0.722
## windSpeed                      NA             NA       NA     1.000             0.196
## precipProbability              NA             NA       NA        NA             1.000</code></pre>
<p>Finally, in order to plot this, the data needs to be in tidy (or long) format. Here we convert the <code>things_to_correlate</code> matrix into a data frame, add a column for the row names, take all the columns and put them into a single column named <code>measure1</code>, and take all the correlation numbers and put them in a column named <code>cor</code> In the end, we make sure the measure variables are ordered by their order of appearance (otherwise they plot alphabetically and don’t make a triangle)</p>
<pre class="r"><code>things_to_correlate_long &lt;- things_to_correlate %&gt;%
  # Convert from a matrix to a data frame
  as.data.frame() %&gt;%
  # Matrixes have column names that don&#39;t get converted to columns when using
  # as.data.frame(), so this adds those names as a column
  rownames_to_column(&quot;measure2&quot;) %&gt;%
  # Make this long. Take all the columns except measure2 and put their names in
  # a column named measure1 and their values in a column named cor
  pivot_longer(cols = -measure2,
               names_to = &quot;measure1&quot;,
               values_to = &quot;cor&quot;) %&gt;%
  # Make a new column with the rounded version of the correlation value
  mutate(nice_cor = round(cor, 2)) %&gt;%
  # Remove rows where the two measures are the same (like the correlation
  # between humidity and humidity)
  filter(measure2 != measure1) %&gt;%
  # Get rid of the empty triangle
  filter(!is.na(cor)) %&gt;%
  # Put these categories in order
  mutate(measure1 = fct_inorder(measure1),
         measure2 = fct_inorder(measure2))

things_to_correlate_long</code></pre>
<pre><code>## # A tibble: 10 × 4
##    measure2        measure1              cor nice_cor
##    &lt;fct&gt;           &lt;fct&gt;               &lt;dbl&gt;    &lt;dbl&gt;
##  1 temperatureHigh temperatureLow     0.920      0.92
##  2 temperatureHigh humidity          -0.0301    -0.03
##  3 temperatureHigh windSpeed         -0.377     -0.38
##  4 temperatureHigh precipProbability -0.124     -0.12
##  5 temperatureLow  humidity           0.112      0.11
##  6 temperatureLow  windSpeed         -0.450     -0.45
##  7 temperatureLow  precipProbability -0.0255    -0.03
##  8 humidity        windSpeed          0.0108     0.01
##  9 humidity        precipProbability  0.722      0.72
## 10 windSpeed       precipProbability  0.196      0.2</code></pre>
<p>Phew. With the data all tidied like that, we can make a correlogram with a heatmap. We have manipulated the fill scale a little so that it’s diverging with three colors: a high value, a midpoint value, and a low value.</p>
<pre class="r"><code>ggplot(things_to_correlate_long,
       aes(x = measure2, y = measure1, fill = cor)) +
  geom_tile() +
  geom_text(aes(label = nice_cor)) +
  scale_fill_gradient2(low = &quot;#E16462&quot;, mid = &quot;white&quot;, high = &quot;#0D0887&quot;,
                       limits = c(-1, 1)) +
  labs(x = NULL, y = NULL, fill = &#39;Corr.&#39;) +
  coord_equal() +
  theme_minimal() +
  theme(panel.grid = element_blank())</code></pre>
<p><img src="/example/05-example_files/figure-html/cor-heatmap-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Instead of using a heatmap, we can also use points, which encode the correlation information both as color <em>and</em> as size. To do that, we just need to switch <code>geom_tile()</code> to <code>geom_point()</code> and set the <code>size = cor</code> mapping:</p>
<pre class="r"><code>ggplot(things_to_correlate_long,
       aes(x = measure2, y = measure1, color = cor)) +
  # Size by the absolute value so that -0.7 and 0.7 are the same size
  geom_point(aes(size = abs(cor))) +
  scale_color_gradient2(low = &quot;#E16462&quot;, mid = &quot;white&quot;, high = &quot;#0D0887&quot;,
                        limits = c(-1, 1)) +
  scale_size_area(max_size = 15, limits = c(-1, 1), guide = &#39;none&#39;) +
  labs(x = NULL, y = NULL, color = &#39;Corr.&#39;) +
  coord_equal() +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())</code></pre>
<p><img src="/example/05-example_files/figure-html/cor-points-1.png" width="480" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="simple-regression" class="section level2">
<h2>Simple regression</h2>
<p>We finally get to this week’s material. Although correlation is nice, we eventually may want to visualize regression. The lecture has shown us some very intuitive, straightforward ways to think about regression (aka, a line). Simple regression is easy to visualize, since you’re only working with an <span class="math inline">\(X\)</span> and a <span class="math inline">\(Y\)</span>. For instance, what’s the relationship between humidity and high temperatures during the summer?</p>
<p>First, let’s filter the Atlanta weather data to only look at the summer. We also add a column to scale up the humidity value—right now it’s on a scale of 0-1 (for percentages), but when interpreting regression we talk about increases in whole units, so we’d talk about moving from 0% humidity to 100% humidity, which isn’t helpful, so instead we multiply everything by 100 so we can talk about moving from 50% humidity to 51% humidity. We also scale up a couple other variables that we’ll use in the larger model later.</p>
<pre class="r"><code>weather_atl_summer &lt;- weather_atl %&gt;%
  filter(time &gt;= &quot;2019-05-01&quot;, time &lt;= &quot;2019-09-30&quot;) %&gt;%
  mutate(humidity_scaled = humidity * 100,
         moonPhase_scaled = moonPhase * 100,
         precipProbability_scaled = precipProbability * 100,
         cloudCover_scaled = cloudCover * 100)</code></pre>
<p>Then we can build a simple regression model for the high temperature “regressed on” humidity. First, we’ll use the formula from <a href="content/05-content/#the-regression-line-1">Content 05</a>:</p>
<pre class="r"><code>weather_atl_results = weather_atl_summer %&gt;%
  dplyr::summarize(mu_x = mean(humidity_scaled),
                   mu_y = mean(temperatureHigh),
                   sd_x = sd(humidity_scaled),
                   sd_y = sd(temperatureHigh),
                   rho = sum(((temperatureHigh-mu_y)/sd_y)*((humidity_scaled-mu_x)/sd_x))/(n()-1) ) %&gt;%
                  # Note in rho we had to use that same &quot;N-1&quot; correction. cor() does this for us automatically
  dplyr::mutate(beta_1 = rho*(sd_y/sd_x),
                beta_0 = mu_y - beta_1*mu_x)

print(weather_atl_results)</code></pre>
<pre><code>## # A tibble: 1 × 7
##    mu_x  mu_y  sd_x  sd_y    rho beta_1 beta_0
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  64.8  88.5  10.6  5.33 -0.481 -0.241   104.</code></pre>
<p>Note that the formulas from <a href="content/05-content/#the-regression-line-1">Content 06</a> have a direct translation into the code. Also note that we used <code>summarize</code> on the data so that we get only <strong>one</strong> row of data (no more 1,000+ rows, we’ve summarized them using <code>mean</code> and <code>sd</code>).</p>
<p>We can interpret these coefficients like so:</p>
<ul>
<li><p><code>beta_0</code> (or <span class="math inline">\(\beta_0\)</span>) is the intercept. By definition of an intercept, it shows that the average temperature when there’s <strong>0% humidity</strong> is 104°. There are no days with 0% humidity though, so we can ignore the intercept—it’s really just here so that we can draw the line.</p></li>
<li><p><code>beta_1</code> (or <span class="math inline">\(\beta_1\)</span>) is the coefficient for <code>humidity_scaled</code>. It shows that a one percent increase in humidity is associated with a 0.241° decrease in temperature, on average.</p>
<ul>
<li>This (and <span class="math inline">\(\beta_0\)</span>) are random variables – if we re-draw the sample, we’ll see a slightly different relationship. We’ll talk about the standard error of this in a little bit.</li>
</ul></li>
</ul>
<p>Visualizing this model is simple, since there are only two variables. We visualized the regression line in the Galton Heights data during Content 05, so let’s just use that code.</p>
<pre class="r"><code>ggplot(weather_atl_summer, aes(x = humidity_scaled, y = temperatureHigh)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = weather_atl_results$beta_0, slope = weather_atl_results$beta_1)</code></pre>
<p><img src="/example/05-example_files/figure-html/plot-simple-formula-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Every point along the regression line is the <span class="math inline">\(E[temperatureHigh|humidity scaled]\)</span>. Put in whatever value of humidity you want, and the line tells you what the expectation of the high temperature will be.</p>
<p>Another way we can add a regression line in a 2-D plot is using <code>geom_smooth</code>. <code>geom_smooth</code> is a <code>ggplot</code> geometry that adds a line of best fit. This can be flexible, or this can be based on a linear relationship – the regression line. We’ll see how to use built-in functions in R to do regression later, but for now, we’ll just ask ggplot to make a <strong>l</strong>inear <strong>m</strong>odel (“lm”) for a line of best fit. The slope of that line is going to be exactly our estimate of <span class="math inline">\(\beta_1\)</span>.</p>
<pre class="r"><code>ggplot(weather_atl_summer,
       aes(x = humidity_scaled, y = temperatureHigh)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="/example/05-example_files/figure-html/plot-simple-model-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>And indeed, we see the same line as we made “manually” before.</p>
<div class="fyi">
<p><strong>TRY IT</strong></p>
<p>Let’s use that <code>RECS</code> data to regress <code>EnergyUsed</code> on one of the variables from your scatterplot matrix. Note that we say the left-hand-side variable (the “Y”) is <em>regressed on</em> the right-hand-side (the “X”) variable.</p>
<p>Using the formulas and codes for regression, choose the variable you want to use in the regression, run it, and visualize the result.</p>
</div>
</div>

                    </div>

                    



                    
                </div>

                <div class="body-footer">
                    <p>Last updated on February 8, 2024</p>

                    


                    

                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>SSC 442: Data Analytics (Spring Semester 2024)</strong><br>

                <a href="https://www.msu.edu" target="_blank" rel="noopener">Michigan State University</a> &emsp;&emsp;
                <a href="https://socialscience.msu.edu/" target="_blank" rel="noopener">College of Social Science</a>
            </p>

            <p>
                <a href="https://www.benbushong.com" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Prof. Ben Bushong</a> &emsp;&emsp;
                <a href="mailto:bbushong@msu.edu"><i class="fas fa-envelope"></i>
                    bbushong@msu.edu</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Tuesday and Thursday &emsp;&emsp;
                <i class="far fa-clock"></i> 12:40pm - 2:00pm 
                <br><i class="fas fa-university"></i> 204 Natural Sciences
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2020-24 <a href="https://www.benbushong.com" target="_blank" rel="noopener">Ben Bushong; Justin Kirkpatrick; based on work by Andrew Heiss</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    

    
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.a21fcc4a4cdf5eeefae0603e61b3030c.js"></script>

    



    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
